# Generated by Django 4.2.3 on 2023-07-30 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
