# Generated by Django 4.2.3 on 2023-07-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Novel',
        ),
    ]
