# Generated by Django 4.2.3 on 2023-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackbooks', '0002_rename_book_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='novel_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
